---
abstract: 'SPARQL extension for App-perlrdf'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::perlrdf::Command::Query
name: App-perlrdf-Command-Query
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  App::perlrdf: 0
  JSON: 2.00
  RDF::Query: 2.900
  RDF::Query::Client: 0.112
  Spreadsheet::Wright: 0
  YAML::XS: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=App-perlrdf-Command-Query
  homepage: https://metacpan.org/release/App-perlrdf-Command-Query
  license: http://dev.perl.org/licenses/
version: 0.002
